### ISSUE TITLE
possible error in utils.originalURL

### ISSUE THREAD

**Issue by pmwaldemar** [camme/passport-http-2legged-oauth#3]
Hello,

I may have found an issue in your utils.originalURL if used with Express.js.
It's in the line 32:
`path = req.url || '';`

Express.js adds the attribute req.originalUrl that keeps the orignal URL, while req.url is changed during express' routing process. If you set the path to req.originalUrl if the attribute is defined it works better with Express.

http://expressjs.com/api#req.originalUrl

If this is a misunderstanding on my side could you be so kind to explain it to me? :)

Thanks in advance

**Comment by bayareagreg** [comment]
I came accross the same issue and the proposed fix worked for me.
Thanks
Greg
