### ISSUE TITLE
NPM Publish

### ISSUE THREAD

**Issue by cthorne66** [camme/passport-http-2legged-oauth#9]
Hi,

Can you re-publish to NPM please? Currently missing this change to lib/utils.js in the NPM version

``` javascrip
exports.originalURL = function(req, defaultHost) {
  var headers = req.headers
    , protocol = (req.connection.encrypted || req.headers['x-forwarded-proto'] == 'https')
               ? 'https'
               : 'http'
    , host = defaultHost || headers.host
    , path = req.originalUrl || req.url || '';
  return protocol + '://' + host + path;
};
```

Took me a while to find this.

Thank you
Chris

**Comment by cthorne66** [comment]
To provide some more context this becomes relevant when using modular routers as described in the Express JS v4 documentation.

Thank you

**Comment by amatelin** [comment]
+ 1

**Comment by linuws** [comment]
+1 - @camme do you think you can find the time?

**Comment by camme** [comment]
I'm sorry that I missed this. I completely missed the github notifications about this issue.
It should be published now.
